Fix/revisit get_package
twisted/towncrier pull request #176
Opened 2020-03-09 00:20 UTC by blueyed

Try importing without changing `sys.path` first.

This makes a difference for pytest, where it would fail to
`from _pytest._version import version`, since `_pytest._version` does
not exist in the source tree (with non-editable installs), but only
the installed package.

It also improves the error reporting:

- prefix with "ERROR" for what might be redirected
- raise the `ImportError` directly (more information than when wrapped
  in `Exception`)

Ref: https://github.com/pytest-dev/pytest/issues/6831

2020-03-09 00:21 UTC, blueyed commented on src/towncrier/_project.py
> +        # Yes, that means importing it. Call the cops, I don't care.
I've kept this comment as is, but might make sense to rephrase - there was never a step 1 for example.

2020-03-09 00:21 UTC, hawkowl commented
# [Codecov](https://codecov.io/gh/hawkowl/towncrier/pull/176?src=pr&el=h1) Report
> Merging [#176](https://codecov.io/gh/hawkowl/towncrier/pull/176?src=pr&el=desc) into [master](https://codecov.io/gh/hawkowl/towncrier/commit/fff788d80bf348809eab720fb56d00b2a217e6b5&el=desc) will **increase** coverage by `0.04%`.
> The diff coverage is `44.44%`.

[![Impacted file tree graph](https://codecov.io/gh/hawkowl/towncrier/pull/176/graphs/tree.svg?width=650&height=150&src=pr&token=9npndnog2E)](https://codecov.io/gh/hawkowl/towncrier/pull/176?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #176      +/-   ##
==========================================
+ Coverage   89.54%   89.59%   +0.04%     
==========================================
  Files          11       11              
  Lines         440      442       +2     
  Branches       85       83       -2     
==========================================
+ Hits          394      396       +2     
  Misses         25       25              
  Partials       21       21              
```


| [Impacted Files](https://codecov.io/gh/hawkowl/towncrier/pull/176?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/towncrier/\_project.py](https://codecov.io/gh/hawkowl/towncrier/pull/176/diff?src=pr&el=tree#diff-c3JjL3Rvd25jcmllci9fcHJvamVjdC5weQ==) | `58.97% <44.44%> (+2.21%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/hawkowl/towncrier/pull/176?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/hawkowl/towncrier/pull/176?src=pr&el=footer). Last update [fff788d...a7a0701](https://codecov.io/gh/hawkowl/towncrier/pull/176?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

2020-03-09 00:23 UTC, blueyed commented on src/towncrier/_project.py
> +        # Yes, that means importing it. Call the cops, I don't care.
Done in a fixup (please squash-merge): it also fixes the sys.path.pop.

2020-11-27 15:57 UTC, altendky requested changes
Would it be reasonable to setup a test for this?  It seems like a feature addition so a newsfragment would be useful?  Thanks for the help here.

2020-12-13 03:08 UTC, altendky commented
If you get back to this before I manage to find some reviews, feel free to merge #297 back in here and we can continue with this PR and close mine.  I just didn't want to hijack your branch.  Thanks again.

2020-12-13 08:40 UTC, blueyed commented
Cool, closing then.

2020-12-13 08:40 UTC, closed without merging