Add title_format tests and drop a line
twisted/towncrier pull request #299
Opened 2020-12-14 01:26 UTC by altendky

2020-12-20 12:05 UTC, adiroiban approved these changes
Looks good.

I am not sure what is the scope of this PR and why we need it.

I would argue that we don't need to support `false` so don't add extra test for it... but at the same time we don't need to add extra logic for it.

I would say that only having`test_title_format_non_empty` is enough for this PR.

Thanks!

2020-12-20 12:05 UTC, adiroiban commented on src/towncrier/test/test_build.py
> +    def test_title_format_non_empty(self):
```suggestion
    def test_title_format_custom(self):
```

2020-12-20 12:09 UTC, adiroiban requested changes
I see this in the docs

`title_format = "{name} {version} ({project_date})"  # or false if template includes title`

And now I am confused...

I think that we should change README as part of this PR to make it clear how title_format should be used and what is the purpose of setting it to false.

2020-12-20 15:42 UTC, altendky commented
Explanation was certainly lacking.  This followed from https://github.com/twisted/towncrier/issues/164 where it was reported that `title_format = false` in the configuration file was not working properly.  The code had been fixed by 19.9.0rc1 but I didn't see any tests so I figured it was worth adding a test in response to the ticket rather than just closing the ticket.

My understanding is that if you specify a template which includes the title then you should specify `title_format = false` to avoid doubling up on titles (your template plus the default title format).  So, switch this from misc to a doc news fragment, provide an explanation in the readme, and keep both tests?

After we agree on that I'll handle the rest of the details.

2020-12-20 16:11 UTC, adiroiban commented
> My understanding is that if you specify a template which includes the title then you should specify `title_format = false` to avoid doubling up on titles (your template plus the default title format). So, switch this from misc to a doc news fragment, provide an explanation in the readme, and keep both tests?

OK. I guess that we should have a separate section to explain each option... and not show them as an example with a brief comment.

So, my understanding is:

```
title_format = "{name} {version} ({project_date})"

Use this option to define format the title for each release.
Available placeholders are:
* name - name of the project
* version - current version of the project
* project_date - date when the version was/is released

Leave it out or set it to empty string to use the default towncrier format.
Set it to `false`  to not have townrier generate a tiltte. For the case in which your custom template is defining its own title.
```

And yes. the docstring for each test could be verbose and explain each tests case and what functionality is tested.

2020-12-20 16:19 UTC, adiroiban approved these changes
With better documentation this can be merged.

2020-12-20 17:00 UTC, altendky commented on src/towncrier/test/test_build.py
> +            abc FooBarBaz 7.8.9 (01-01-2001)
```suggestion
            [{01-01-2001}] CUSTOM RELEASE for FooBarBaz version 7.8.9
```

2020-12-20 17:01 UTC, altendky commented on src/towncrier/test/test_build.py
> +        Setting the title format to false disables the explicit title.
I think this was addressed with the explanation of a `false` value.

2020-12-20 17:02 UTC, altendky commented on src/towncrier/test/test_build.py
> +            FooBarBaz 7.8.9 (01-01-2001)
```suggestion
            FooBarBaz 7.8.9 (20-01-2001)
```

2020-12-20 17:03 UTC, altendky commented on src/towncrier/test/test_build.py
> +                    "01-01-2001",
```suggestion
                    "20-01-2001",
```

2020-12-20 17:03 UTC, altendky commented on src/towncrier/test/test_build.py
> +                f.write("Adds levitation")
```suggestion
```

2020-12-20 17:04 UTC, altendky commented on src/towncrier/test/test_build.py
> +            - Adds levitation (#123)
```suggestion
```

2020-12-20 19:43 UTC, merged

2021-04-25 11:19 UTC, vytas7 commented on src/towncrier/test/test_build.py
> +            FooBarBaz 7.8.9 (20-01-2001)
I missed this when reporting the fix worked for me... This is well incorrect, the title should not appear here as per `title_format = false` above?