bugfix in _writer.py
twisted/towncrier pull request #391
Opened 2022-06-24 09:47 UTC by mikesongming

the version-already-produced error raising cannot be reached in expected single file mode like the test case in :test_write:WritingTests.test_append_at_top_with_hint

2022-06-24 15:41 UTC, mikesongming commented
> Thanks for the update.
> 
> I only see this about single file
> 
> > If a single file is used, the content of that file gets overwritten each time.
> 
> Can you add more info about why someone would want to use this and how to use it?
> 
> Maybe the automated tests should be updated the reflect the real usage.
> 
> Note I am just doing "emergency reviews" for this project.
> 
> If the tests are green we can merge this PR. No problem.
> 
> But if you are using the "single file" feature it would be nice to document it and make sure the automated tests will fail if any future change will introduce regressions for this feature.

After reading docs and source code of `v21.9.0`, I guess that there are two use cases for the `single_file` flag:

1. `single_file=true`   :  the default choice for most projects. People hopes to have only one fixed **news file** given by the confiuration option `filename`, and  in each `towncrier build` to packed newly versioned change log at the top of **news file**. In case of duplicate version submitting, some author added the "version-already-produced error raising" code in _write.py:29-30 as: 
```
    if top_line and top_line in existing_content:
        raise ValueError("It seems you've already produced newsfiles for this version?")
```
However, that branch of code woule never be triggered due to the 'splitting by start_string' and writing logic afterwards.

2. `single_file=false` : in some unknown scenario, people may hope writing to unique news files in each `towncrier build` run, as [depicted in docs](https://towncrier.readthedocs.io/en/latest/index.html?highlight=single_file#further-options): 
> single_file = true  # if false, filename is formatted like `title_format`.
However, build.py:196:200 implemented in the reverse direction:

 ```
       if config["single_file"]:
            # When single_file is enabled, the news file name changes based on the version.
            news_file = news_file.format(
                name=project_name, version=project_version, project_date=project_date
            )
```

Hope my explanation helps and booth discrepancies have been fixed in this PR. 

My another issue #390 has extracted related code snippets for details.

2022-07-09 19:49 UTC, mikesongming commented
@adiroiban please hold the PR, additional fixes needed

2022-07-09 20:20 UTC, mikesongming commented
@adiroiban After adding a news fragment, ci workflow passed with all success. Please check and approve the PR.

https://github.com/twisted/towncrier/actions/runs/2642268377

2022-07-10 10:19 UTC, adiroiban commented on src/towncrier/build.py
>              # When single_file is enabled, the news file name changes based on the version.
Is this change ok ?

I was expecting something like this

```suggestion
        if config["single_file"] is True:
            # When single_file is enabled,
            # the release notes for each version are stored in a separate file.
            # The name of that file is generated based on the current version and project.
```

2022-07-10 10:57 UTC, adiroiban commented on src/towncrier/newsfragments/391.bugfix
> +
I think that we have 2 separate issues here.

* The detection of duplicate release notes was fixed and SOME PREVIOUS BEHAVIOUR is no longer triggered.
* Support for having the release notes for each version in a separate file is working again. This is regression introduced in VERSION X.Y.Z.

2022-07-10 10:58 UTC, adiroiban commented on src/towncrier/test/test_build.py
> +        Disabling the single file mode will write the changelog to a filename
I think that the docstring of the tests should be self contained and not link to the documentation.

It should explain the targeted feature, regardless of the documentation.

In some way, the docstring of  this test serves as the "real" documentation :)

2022-07-10 11:14 UTC, adiroiban commented on src/towncrier/test/test_build.py
> +            single_file = true  # if false, filename is formatted like `title_format`.
```suggestion
        When `single_file = false` the release notes for each version are stored
        in a separate file.
        The name of the file is defined by the `title_format` configuration value.
```

2022-07-10 11:16 UTC, adiroiban commented on src/towncrier/test/test_build.py
> +                )
A bit easier to read.
```suggestion
                f.write(
                    '[tool.towncrier]\n'
                    ' single_file=false\n'
                    ' filename="{version}-notes.rst"\n'
                    ''
                )
```

2022-07-10 11:17 UTC, adiroiban commented on src/towncrier/test/test_build.py
> +    def test_single_file_false(self):
maybe a better description of the targeted feature

```suggestion
    def test_release_notes_in_separate_files(self):
```

2022-07-10 11:19 UTC, adiroiban commented on src/towncrier/test/test_build.py
> +    def test_single_file(self):
Maybe a better description for the feature

```suggestion
    def test_all_version_notes_in_a_single_file(self):
```

2022-07-10 11:21 UTC, adiroiban commented on src/towncrier/test/test_build.py
> +        "If a single file is used, the content of that file gets overwritten each time."
```suggestion
        When `single_file = true` the single file is used to store the notes
        for multiple versions.
        
        The name of the file is fixed and is not extrapolated with any variable.
```

2022-07-10 11:22 UTC, adiroiban commented on src/towncrier/test/test_build.py
> +                )
I think that this is the important part.
```suggestion
                f.write(
                    '[tool.towncrier]\n'
                    ' single_file=true\n'
                    ' # The `filename` variable is fixed and not formated\n`
                    ' # in any way.\n'
                    ' filename="{version}-notes.rst"\n
                    ''
                )
```

2022-07-10 11:24 UTC, adiroiban requested changes
Changes for the single_file looks good.

The variable name is confusing :( ... so dedicated documentation should help a lot.

------------

This needs-changes and I am not sure that the `if top_line and top_line in existing_content[-1]:` change is ok.

Do we have tests for this?
Was any of the existing test failing?
 
Maybe have this in a separate PR.

Thanks again

2022-07-11 04:35 UTC, mikesongming commented on src/towncrier/_writer.py
> +    if top_line and top_line in existing_content[-1]:
It should be ok. 

I guess you mean "start marker" as the head line "Release Notes" in front of the `start_string` in my test case? 
Similar changelog setting also appears in the test case `test_write.WritingTests.test_append_at_top_with_hint`:

```
        with open(os.path.join(tempdir, "NEWS.rst"), "w") as f:
            f.write(
                "Hello there! Here is some info.\n\n"
                ".. towncrier release notes start\nOld text.\n"
            )
```

Whether have a "start marker" or not, the struct of `single_file` newsfile would be:
```
[start marker]

[start string]

top_line     # for newer version 
content     # for newer version

top_line     # for older version
content     # for older version

...
```
After the clause `existing_content = existing_content.split(start_string, 1)`, `existing_content` becomes a list:

```
[ start_marker, start_string, previous_changes ]
```
or just `[previous_changes ]`.

In either case, the original predicate `top_line in existing_content` always fails and the supposed raise never happens. That's why I use `top_line in existing_content[-1]` to judge if `top_line` appears in previous content.

2022-07-11 04:59 UTC, mikesongming commented on src/towncrier/test/test_build.py
> +                )
It is really tedious 😂

2022-07-11 05:57 UTC, mikesongming commented
@adiroiban All suggested changes in upon comments have been updated, and a detailed explanation about `single_file` is also updated in README.rst. 

Question about `if top_line and top_line in existing_content[-1]:` part is replied in the comments.

All existing tests passed in the workflow.

2022-07-11 11:41 UTC, adiroiban approved these changes
many thanks for the wonderful work.

Hope all is green and I will merge.

2022-07-11 11:42 UTC, merged

2022-07-14 01:04 UTC, mikesongming commented
glad to make a contribution to towncrier :)